### ISSUE TITLE
Invalid URN format in reply to `texts` request

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/citemicroservices#1]
Values in URN list are missing final ":" separating work definition from (empty) passage component.

**Comment by ThomasK81** [comment]
I wasn't aware that you want the last colon ":". I am happy to integrate it, but is this wise? does that mean if we would want to get all urns from a urn we would have to send `http://localhost:8080/texts/urns/urn:cts:citeArch:groupA.work1.ed2:` instead of `http://localhost:8080/texts/urns/urn:cts:citeArch:groupA.work1.ed2`?

**Comment by ThomasK81** [comment]
Fixed. Implementation decision was that it also accepts it without the colon from the user using the http request, BUT it only returns urns with 5 colons.
